Feature/user state management
tempakyousuke/sveltekit-blog pull request #10
Opened 2021-09-19 18:59 UTC by tempakyousuke

以下の対応をしました
- signup後 `/`にリダイレクト (signup直後は未承認であるため)
- signin後 `/admin`にリダイレクト
- ログインしていない状態で`/admin`にアクセスした場合`/signin`にリダイレクト

2021-09-20 16:50 UTC, yasudanaoya requested changes

2021-09-20 16:50 UTC, yasudanaoya commented on src/modules/store/store.ts
> +export const user = writable({ uid: '', name: '', allowed: false, isLoggedIn: false });
せっかく ts で書くので、 ユーザーオブジェクトの中身の type を定義した方が良いかなと
少し調べたところ
```ta
import { writable, Writable } from 'svelte/store';
```

```suggestion
type User = {
  ...
}

export const user: Writable<User> = writable({ uid: '', name: '', allowed: false, isLoggedIn: false });
```

こんな書き方ができるみたいです

https://javascript.plainenglish.io/writing-a-svelte-store-with-typescript-22fa1c901a4

2021-09-21 11:11 UTC, tempakyousuke commented on src/modules/store/store.ts
> +export const user = writable({ uid: '', name: '', allowed: false, isLoggedIn: false });
修正しました

2021-09-22 12:11 UTC, yasudanaoya commented on types/user.d.ts
> +export interface LoginUser {
.d.ts ファイルでアプリ内のデータ型定義したことなくてよくわかってないんですが
（僕が普段 .ts ファイルに定義しちゃっているせい）

公式を読むと、1行目？に declare を定義するのが正しいみたいですが、付けなくて lint だったりとかにおこられてないですかね？

> ファイルの拡張子が.d.tsの場合、各ルートレベルの定義にはdeclareというキーワードを前に付ける必要があります。これは、TypeScriptによって生成されるコードがないことを開発者に対して明確にするのに役立ちます。開発者は、宣言された項目が実行時に存在することを確認する必要があります。

https://typescript-jp.gitbook.io/deep-dive/type-system/intro/d.ts

2021-09-22 13:23 UTC, tempakyousuke commented on types/user.d.ts
> +export interface LoginUser {
アンビエント宣言で調べた結果.d.tsにしなくていいことがわかったので、tsに直します。

2021-09-22 13:35 UTC, tempakyousuke commented on types/user.d.ts
> +export interface LoginUser {
直しました

2021-09-26 05:34 UTC, yasudanaoya approved these changes
![LGTM](https://media.giphy.com/media/jNdw5Qmy5MOpq/giphy.gif)

2021-09-26 05:34 UTC, merged