create signup and signin page
tempakyousuke/sveltekit-blog pull request #9
Opened 2021-09-16 19:50 UTC by tempakyousuke

ログインと新規登録機能をつけました。
一般公開するつもりはないので、URL知ってる人だけが使う想定でいます。
/signupで登録した後、firebaseのコンソールで該当のuserデータのallowedをtrueにして、該当ユーザーがブログを投稿できるようにします。

2021-09-17 13:26 UTC, yasudanaoya requested changes

2021-09-17 13:26 UTC, yasudanaoya commented on firestore.rules
> +      allow create, update: if request.auth.uid == uid && request.resource.data.allowed != true;
=== 、厳密等価じゃない理由ってありますか？

2021-09-17 13:26 UTC, yasudanaoya commented on src/lib/button/BaseButton.svelte
> +	};
disable だったら実行しない。
よりも disable だったらクリックできない。の方が  HTML 的に正しい気がしてます

なので、
buttunEl の disabled 属性に変更加えた方が良いかと

2021-09-17 13:26 UTC, yasudanaoya commented on src/routes/signin.svelte
> +				console.log(error);
めっちゃ細かいけど
```suggestion
				console.error(error);
```
とかの方が正しい気がします

2021-09-17 19:45 UTC, tempakyousuke commented on firestore.rules
> +      allow create, update: if request.auth.uid == uid && request.resource.data.allowed != true;
rulesの文法なので==がすでに厳密等価です。

2021-09-17 19:46 UTC, tempakyousuke commented on src/routes/signin.svelte
> +				console.log(error);
そのようにしました

2021-09-17 20:24 UTC, tempakyousuke commented on src/lib/button/BaseButton.svelte
> +	};
変えました

2021-09-18 16:56 UTC, yasudanaoya commented on firestore.rules
> +      allow create, update: if request.auth.uid == uid && request.resource.data.allowed != true;
なるほど。

2021-09-18 16:56 UTC, yasudanaoya approved these changes
![LGTM](https://pbs.twimg.com/media/DDeUOoQV0AI4aft.png)

2021-09-18 16:56 UTC, merged